name: Module-Install-GetProgramLocations
version: 0.10.0
abstract: A Module::Install extension that allows
author: David Coppit <david@coppit.org>
license: gpl
distribution_type: module
requires:
  File::Spec: Cwd
  Sort::Versions: Module::Install
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
