name: Module-Install-GetProgramLocations
version: 0.3001
abstract: A Module::Install extension that allows
author: David Coppit <david@coppit.org>
license: gpl
distribution_type: module
requires:
  File::Spec: 0
  Cwd: 0
  Sort::Versions: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
